services:
  mois-microservice-reservations:
    container_name: mois-microservice-reservations
    build: .
    depends_on:
      - mois-microservice-reservations-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${RESERVATIONS_PORT}:3000"

  mois-microservice-reservations-db:
    container_name: mois-microservice-reservations-db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RESERVATIONS_DATABASE_USER}
      POSTGRES_PASSWORD: ${RESERVATIONS_DATABASE_PASSWORD}
      POSTGRES_DB: ${RESERVATIONS_DATABASE_DB}
    restart: unless-stopped
#    ports:
#      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RESERVATIONS_DATABASE_USER} -d ${RESERVATIONS_DATABASE_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mois-microservice-reservations-adminer:
    image: adminer
    container_name: mois-microservice-reservations-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mois-microservice-reservations-db
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  postgres_data:
